export const jwtConstants = {
  secret: 'your-secret-key', // Replace with a strong secret key
};
export const SPRINT_PREFIX = 'Sprint-';

export const DEFAULT_PRIORITY = [
  { name: 'High', priority: 1, colorCode: '#FF3E46' },
  { name: 'Medium', priority: 2, colorCode: '#FB774A' },
  { name: 'Low', priority: 3, colorCode: '#674AFF' },
];

export const TASK_STATUS_DEFAULT_COLOR = [
  { name: 'Waiting for Approval', colorCode: '#FFC107' },
  { name: 'Ready for Testing', colorCode: '#4CAF50' },
  { name: 'Needs Verification', colorCode: '#FF5722' },
  { name: 'In Review', colorCode: '#2196F3' },
  { name: 'In Design', colorCode: '#9C27B0' },
  { name: 'In Development', colorCode: '#FF9800' },
  { name: 'In QA', colorCode: '#E91E63' },
  { name: 'Waiting for Feedback', colorCode: '#673AB7' },
  { name: 'Pending Approval', colorCode: '#795548' },
  { name: 'On Hold by Client', colorCode: '#607D8B' },
  { name: 'Ready for Deployment', colorCode: '#009688' },
  { name: 'Pending Deployment', colorCode: '#FFEB3B' },
  { name: 'In Progress - Pending Feedback', colorCode: '#03A9F4' },
  { name: 'Blocked by Dependency', colorCode: '#FF5722' },
  { name: 'In Review - Pending Changes', colorCode: '#F44336' },
  { name: 'In Progress - Partially Completed', colorCode: '#FFC107' },
  { name: 'Pending Validation', colorCode: '#4CAF50' },
  { name: 'Waiting for Customer Response', colorCode: '#9C27B0' },
  { name: 'Pending Prioritization', colorCode: '#673AB7' },
  { name: 'In Review - Approved', colorCode: '#009688' },
  { name: 'In Review - Rejected', colorCode: '#F44336' },
  { name: 'In Maintenance', colorCode: '#FF9800' },
  { name: 'Waiting for Resources', colorCode: '#E91E63' },
  { name: 'Inactive', colorCode: '#795548' },
  { name: 'Pending Payment', colorCode: '#607D8B' },
  { name: 'Deferred Maintenance', colorCode: '#2196F3' },
  { name: 'Pending Closure', colorCode: '#FFEB3B' },
  { name: 'Needs Attention', colorCode: '#03A9F4' },
  { name: 'Investigating', colorCode: '#FF5722' },
  { name: 'New', colorCode: '#4CAF50' },
  { name: 'In Progress', colorCode: '#FFC107' },
  { name: 'Completed', colorCode: '#9C27B0' },
  { name: 'On Hold', colorCode: '#FF5722' },
  { name: 'Cancelled', colorCode: '#2196F3' },
  { name: 'Blocked', colorCode: '#E91E63' },
  { name: 'Pending Review', colorCode: '#795548' },
  { name: 'Deferred', colorCode: '#607D8B' },
  { name: 'Reopened', colorCode: '#FF9800' },
  { name: 'Duplicate', colorCode: '#673AB7' },
  { name: 'Invalid', colorCode: '#9C27B0' },
  { name: "Won't Fix", colorCode: '#FF5722' },
  { name: 'Postponed', colorCode: '#03A9F4' },
  { name: 'Scheduled', colorCode: '#FFEB3B' },
  { name: 'In Testing', colorCode: '#4CAF50' },
  { name: 'Deployed', colorCode: '#2196F3' },
  { name: 'Archived', colorCode: '#FF9800' },
  { name: 'Closed', colorCode: '#795548' },
];

export const TASK_TYPE_DEFAULT_COLOR = [
  { name: 'BUG', colorCode: '#FF5733' },
  { name: 'TASK', colorCode: '#2196F3' },
  { name: 'STORY', colorCode: '#4CAF50' },
  { name: 'SUBTASK', colorCode: '#FFC107' },
  { name: 'ENHANCEMENT', colorCode: '#9C27B0' },
  { name: 'EPIC', colorCode: '#795548' },
  { name: 'RESEARCH', colorCode: '#607D8B' },
  { name: 'DOCUMENTATION', colorCode: '#FF9800' },
  { name: 'MEETING', colorCode: '#673AB7' },
  { name: 'DEPLOYMENT', colorCode: '#E91E63' },
];
